"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navBar";
import gsap from "gsap";
import SplashScreenManager from "./components/SplashScreenManager";
import ScrollTrigger from "gsap-trial/ScrollTrigger";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
gsap.registerPlugin(ScrollTrigger);
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SplashScreenManager>{children}</SplashScreenManager>
      </body>
    </html>
  );
}
