"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap-trial/dist/ScrollTrigger";
import { ScrollSmoother } from "gsap-trial/dist/ScrollSmoother";
import gsap from "gsap-trial/dist/gsap";
import { usePathname } from "next/navigation";
import { useRef } from "react";
import useIsomorphicLayoutEffect from "@/helper/isomorphicEffect";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger, ScrollSmoother, useGSAP);
}

export default function RootLayout({ children }) {
  const smoother = useRef();
  const ctx = useRef();
  const pathname = usePathname();

  useIsomorphicLayoutEffect(() => {
    gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

    ctx.current = gsap.context(() => {
      smoother.current = ScrollSmoother.create({
        smooth: 2,
        effects: true,
      });
    });

    return () => ctx.current.revert();
  }, [pathname]);
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <div id="smooth-wrapper">
          <div id="smooth-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
